<?php
return [
    'slide_1_title' => 'Integrated Goods Supervision',
    'slide_1_desc' => 'A centralized system to ensure smooth and secure supervision processes.',
    'slide_1_cta' => 'Contact Us',
    'fitur' => 'Key Features',

    'feature_1_title' => 'Automated Recording',
    'feature_1_desc' => 'Supports fast and accurate item data recording without manual steps.',

    'feature_2_title' => 'Document Verification',
    'feature_2_desc' => 'Ensures the validity of documents generated by the system.',

    'feature_3_title' => 'Access Control',
    'feature_3_desc' => 'Manages user permissions to maintain data confidentiality and security.',

    'feature_4_title' => 'Goods Management',
    'feature_4_desc' => 'Tracks item movement, stock, and storage locations.',

    'feature_5_title' => 'Procedural Audit',
    'feature_5_desc' => 'Reviews processes and procedures for compliance with standards.',

    'feature_6_title' => 'Warehouse Integration',
    'feature_6_desc' => 'Directly connected with warehouse systems for efficient goods supervision.',

    'feature_7_title' => 'Latest Reports',
    'feature_7_desc' => 'Accurate data to support decision-making.',

    'feature_8_title' => 'Inspection Reports',
    'feature_8_desc' => 'Provides inspection results for further evaluation.',

    'feature_9_title' => 'Multi-Level Access',
    'feature_9_desc' => 'User control based on roles.',
];
